del MakeFile
del _Libs\MakeFile
del _Libs\MakeFile*
del _Libs\SDL2_mixer_modified\MakeFile
del _Libs\SDL2_mixer_modified\MakeFile*
del _Libs\luabind\_project\MakeFile
del _Libs\luabind\_project\MakeFile*
del _Libs\oolua\project\MakeFile
del _Libs\oolua\project\MakeFile*
del Editor\MakeFile
del Editor\MakeFile*
del Engine\MakeFile
del Engine\MakeFile*
del GIFs2PNG\MakeFile
del GIFs2PNG\MakeFile*
del LazyFixTool\MakeFile
del LazyFixTool\MakeFile*
del PNG2GIFs\MakeFile
del PNG2GIFs\MakeFile*
del PlayableCalibrator\MakeFile
del PlayableCalibrator\MakeFile*
pause
