# Major
set(ENGINE_VERSION_1 0)
# Minor
set(ENGINE_VERSION_2 3)
# Revision
set(ENGINE_VERSION_3 3)
# Patch
set(ENGINE_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(ENGINE_VERSION_REL "-dev")

add_definitions(-DENGINE_VERSION_1=${ENGINE_VERSION_1})
add_definitions(-DENGINE_VERSION_2=${ENGINE_VERSION_2})
add_definitions(-DENGINE_VERSION_3=${ENGINE_VERSION_3})
add_definitions(-DENGINE_VERSION_4=${ENGINE_VERSION_4})
add_definitions(-DENGINE_VERSION_REL=${ENGINE_VERSION_REL})

set(ENGINE_VERSION_STRING "${ENGINE_VERSION_1}.${ENGINE_VERSION_2}")

if(NOT ${ENGINE_VERSION_3} EQUAL 0 OR NOT ${ENGINE_VERSION_4} EQUAL 0)
    string(CONCAT ENGINE_VERSION_STRING "${ENGINE_VERSION_STRING}" ".${ENGINE_VERSION_3}")
endif()

if(NOT ${ENGINE_VERSION_4} EQUAL 0)
    string(CONCAT ENGINE_VERSION_STRING "${ENGINE_VERSION_STRING}" ".${ENGINE_VERSION_4}")
endif()

if(NOT "${ENGINE_VERSION_REL}" STREQUAL "")
    string(CONCAT ENGINE_VERSION_STRING "${ENGINE_VERSION_STRING}" "${ENGINE_VERSION_REL}")
endif()

message("== Engine version ${ENGINE_VERSION_STRING} ==")
