/*
 * Platformer Game Engine by Wohlstand, a free platform for game making
 * Copyright (c) 2014-2015 Vitaly Novichkov <admin@wohlnet.ru>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "autocodecompiler.h"

AutocodeCompiler::AutocodeCompiler(QList<EventCommand *> commands, QObject *parent) :
    BasicCompiler(commands, parent)
{}

AutocodeCompiler::~AutocodeCompiler()
{}

QString AutocodeCompiler::compileCode()
{
    QString compiledCode;
    compiledCode += "//This code was generated by PGE!\n";
    compiledCode += "//You're free to modify this code but recompiling will overwrite\n";
    compiledCode += "//user-modified code!\n\n";

    for(int i = 0; i < m_events.size(); ++i){
        compiledCode += m_events[i]->compileSegment(Script::COMPILER_AUTOCODE, 0);
        compiledCode += "\n\n\n";
    }

    return compiledCode;
}
