# Major
set(PNG2GIFS_VERSION_1 3)
# Minor
set(PNG2GIFS_VERSION_2 0)
# Revision
set(PNG2GIFS_VERSION_3 0)
# Patch
set(PNG2GIFS_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(PNG2GIFS_VERSION_REL "")

add_definitions(-DPNG2GIFS_VERSION_1=${PNG2GIFS_VERSION_1})
add_definitions(-DPNG2GIFS_VERSION_2=${PNG2GIFS_VERSION_2})
add_definitions(-DPNG2GIFS_VERSION_3=${PNG2GIFS_VERSION_3})
add_definitions(-DPNG2GIFS_VERSION_4=${PNG2GIFS_VERSION_4})
add_definitions(-DPNG2GIFS_VERSION_REL=${PNG2GIFS_VERSION_REL})

set(PNG2GIFS_VERSION_STRING "${PNG2GIFS_VERSION_1}.${PNG2GIFS_VERSION_2}")

if(NOT ${PNG2GIFS_VERSION_3} EQUAL 0 OR NOT ${PNG2GIFS_VERSION_4} EQUAL 0)
    string(CONCAT PNG2GIFS_VERSION_STRING "${PNG2GIFS_VERSION_STRING}" ".${PNG2GIFS_VERSION_3}")
endif()

if(NOT ${PNG2GIFS_VERSION_4} EQUAL 0)
    string(CONCAT PNG2GIFS_VERSION_STRING "${PNG2GIFS_VERSION_STRING}" ".${PNG2GIFS_VERSION_4}")
endif()

if(NOT "${PNG2GIFS_VERSION_REL}" STREQUAL "")
    string(CONCAT PNG2GIFS_VERSION_STRING "${PNG2GIFS_VERSION_STRING}" "${PNG2GIFS_VERSION_REL}")
endif()

message("== PNG2GIFs version ${PNG2GIFS_VERSION_STRING} ==")

