set(QT_EXTRA_LIBS)

find_library(QT_PRCE2 qtpcre2)
if(QT_PRCE2)
    # message("==Qt-LibPNG detected! (${QT_PRCE2})==")
    list(APPEND QT_EXTRA_LIBS ${QT_PRCE2})
endif()

find_library(QT_HARFBUZZ qtharfbuzz)
if(QT_HARFBUZZ)
    # message("==Qt-HarfBuzz detected! (${QT_HARFBUZZ})==")
    list(APPEND QT_EXTRA_LIBS ${QT_HARFBUZZ})
endif()

find_library(QT_FREETYPE qtfreetype)
if(QT_FREETYPE)
    # message("==Qt-FreeType detected! (${QT_FREETYPE})==")
    list(APPEND QT_EXTRA_LIBS ${QT_FREETYPE})
endif()

find_library(QT_PNG qtlibpng)
if(QT_PNG)
    # message("==Qt-LibPNG detected! (${QT_PNG})==")
    list(APPEND QT_EXTRA_LIBS ${QT_PNG})
endif()

find_library(QT_PTHREAD pthread)
#if(QT_PTHREAD)
#     message("==pthread detected! (${QT_PTHREAD})==")
#endif()

if(QT_EXTRA_LIBS)
    if("${CMAKE_SYSTEM}" MATCHES "Linux")
	find_library(QT_GLIB glib NAMES glib glib-2.0)
        if(QT_GLIB)
            # message("==GLib detected! (${QT_GLIB})==")
            list(APPEND QT_EXTRA_LIBS ${QT_GLIB})
        endif()
        find_library(QT_DL glib NAMES dl)
        if(QT_DL)
            # message("==DL detected! (${QT_DL})==")
            list(APPEND QT_EXTRA_LIBS ${QT_DL})
        endif()
    endif()
    # message("==Full list of libs: ${QT_EXTRA_LIBS}==")
endif()
