# Major
set(XTCONVERT_VERSION_1 1)
# Minor
set(XTCONVERT_VERSION_2 0)
# Revision
set(XTCONVERT_VERSION_3 0)
# Patch
set(XTCONVERT_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(XTCONVERT_VERSION_REL "")

add_definitions(-DXTCONVERT_VERSION_1=${XTCONVERT_VERSION_1})
add_definitions(-DXTCONVERT_VERSION_2=${XTCONVERT_VERSION_2})
add_definitions(-DXTCONVERT_VERSION_3=${XTCONVERT_VERSION_3})
add_definitions(-DXTCONVERT_VERSION_4=${XTCONVERT_VERSION_4})
add_definitions(-DXTCONVERT_VERSION_REL=${XTCONVERT_VERSION_REL})

set(XTCONVERT_VERSION_STRING "${XTCONVERT_VERSION_1}.${XTCONVERT_VERSION_2}")

if(NOT ${XTCONVERT_VERSION_3} EQUAL 0 OR NOT ${XTCONVERT_VERSION_4} EQUAL 0)
    string(CONCAT XTCONVERT_VERSION_STRING "${XTCONVERT_VERSION_STRING}" ".${XTCONVERT_VERSION_3}")
endif()

if(NOT ${XTCONVERT_VERSION_4} EQUAL 0)
    string(CONCAT XTCONVERT_VERSION_STRING "${XTCONVERT_VERSION_STRING}" ".${XTCONVERT_VERSION_4}")
endif()

if(NOT "${XTCONVERT_VERSION_REL}" STREQUAL "")
    string(CONCAT XTCONVERT_VERSION_STRING "${XTCONVERT_VERSION_STRING}" "${XTCONVERT_VERSION_REL}")
endif()

message("== XTConvert version ${XTCONVERT_VERSION_STRING} ==")

