# Major
set(PALETTEFILTER_VERSION_1 1)
# Minor
set(PALETTEFILTER_VERSION_2 0)
# Revision
set(PALETTEFILTER_VERSION_3 0)
# Patch
set(PALETTEFILTER_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(PALETTEFILTER_VERSION_REL "")

add_definitions(-DPALETTEFILTER_VERSION_1=${PALETTEFILTER_VERSION_1})
add_definitions(-DPALETTEFILTER_VERSION_2=${PALETTEFILTER_VERSION_2})
add_definitions(-DPALETTEFILTER_VERSION_3=${PALETTEFILTER_VERSION_3})
add_definitions(-DPALETTEFILTER_VERSION_4=${PALETTEFILTER_VERSION_4})
add_definitions(-DPALETTEFILTER_VERSION_REL=${PALETTEFILTER_VERSION_REL})

set(PALETTEFILTER_VERSION_STRING "${PALETTEFILTER_VERSION_1}.${PALETTEFILTER_VERSION_2}")

if(NOT ${PALETTEFILTER_VERSION_3} EQUAL 0 OR NOT ${PALETTEFILTER_VERSION_4} EQUAL 0)
    string(CONCAT PALETTEFILTER_VERSION_STRING "${PALETTEFILTER_VERSION_STRING}" ".${PALETTEFILTER_VERSION_3}")
endif()

if(NOT ${PALETTEFILTER_VERSION_4} EQUAL 0)
    string(CONCAT PALETTEFILTER_VERSION_STRING "${PALETTEFILTER_VERSION_STRING}" ".${PALETTEFILTER_VERSION_4}")
endif()

if(NOT "${PALETTEFILTER_VERSION_REL}" STREQUAL "")
    string(CONCAT PALETTEFILTER_VERSION_STRING "${PALETTEFILTER_VERSION_STRING}" "${PALETTEFILTER_VERSION_REL}")
endif()

message("== PaletteFilter version ${PALETTEFILTER_VERSION_STRING} ==")

