find_package(Qt5LinguistTools REQUIRED)

set(MOONDUST_QT_LANG_OUTPUT_DIR "${CMAKE_BINARY_DIR}/bin/languages")
FILE(GLOB MOONDUST_QT_LANG_ICON_FILES "${CMAKE_CURRENT_LIST_DIR}/languages-icons/*.png")

file(GLOB MOONDUST_QT_LANG_SRC_FILES
    "${CMAKE_CURRENT_LIST_DIR}/languages/*.ts"
    "${CMAKE_CURRENT_LIST_DIR}/languages-qt/*.ts"
)

set_source_files_properties(${MOONDUST_QT_LANG_SRC_FILES} PROPERTIES OUTPUT_LOCATION ${MOONDUST_QT_LANG_OUTPUT_DIR})

set(MOONDUST_QT_LANG_BIN_FILES)
qt5_add_translation(MOONDUST_QT_LANG_BIN_FILES ${MOONDUST_QT_LANG_SRC_FILES})
add_custom_target(moondust_translations ALL DEPENDS ${MOONDUST_QT_LANG_BIN_FILES})

if(NOT APPLE)
    file(COPY ${MOONDUST_QT_LANG_ICON_FILES} DESTINATION ${MOONDUST_QT_LANG_OUTPUT_DIR})
    install(FILES ${MOONDUST_QT_LANG_BIN_FILES} DESTINATION "${PGE_INSTALL_DIRECTORY}/languages")
    install(FILES ${MOONDUST_QT_LANG_ICON_FILES} DESTINATION "${PGE_INSTALL_DIRECTORY}/languages")
endif()
