if(NOT PGE_FORCE_QT5 OR Qt6_FOUND)
    find_package(Qt6LinguistTools REQUIRED)
else()
    find_package(Qt5LinguistTools REQUIRED)
endif()

set(MOONDUST_QT_LANG_OUTPUT_DIR "${PGE_DEBUG_DATA}/languages")
FILE(GLOB MOONDUST_QT_LANG_ICON_FILES "${CMAKE_CURRENT_LIST_DIR}/languages-icons/*.png")

file(GLOB MOONDUST_QT_LANG_SRC_FILES
    "${CMAKE_CURRENT_LIST_DIR}/languages/*.ts"
    "${CMAKE_CURRENT_LIST_DIR}/languages-qt/*.ts"
)

set_source_files_properties(${MOONDUST_QT_LANG_SRC_FILES} PROPERTIES OUTPUT_LOCATION ${MOONDUST_QT_LANG_OUTPUT_DIR})

set(MOONDUST_QT_LANG_BIN_FILES)
pge_qt_add_translation(MOONDUST_QT_LANG_BIN_FILES ${MOONDUST_QT_LANG_SRC_FILES})
add_custom_target(moondust_translations ALL DEPENDS ${MOONDUST_QT_LANG_BIN_FILES})

if(NOT APPLE)
    file(COPY ${MOONDUST_QT_LANG_ICON_FILES} DESTINATION ${MOONDUST_QT_LANG_OUTPUT_DIR})
    install(FILES ${MOONDUST_QT_LANG_BIN_FILES} DESTINATION "${PGE_INSTALL_DATA}/languages")
    install(FILES ${MOONDUST_QT_LANG_ICON_FILES} DESTINATION "${PGE_INSTALL_DATA}/languages")
endif()
