set(EDITOR_LANGUAGES
    editor_bg.ts
    editor_de.ts
    editor_en.ts
    editor_es.ts
    editor_fr.ts
    editor_he-IL.ts
    editor_id.ts
    editor_it.ts
    editor_ja.ts
    editor_nl.ts
    editor_pl.ts
    editor_pt.ts
    editor_ru.ts
    editor_sv.ts
    editor_uk.ts
    editor_zh.ts
)

