
// This file has been generated by the GUI designer. Do not modify.
namespace PGEManager
{
	public partial class LaunchEditorWidget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label editorVerLbl;
		
		private global::Gtk.Label engineVerLbl;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Button launchEditorBtn;
		
		private global::Gtk.Button launchEngineBtn;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGEManager.LaunchEditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "PGEManager.LaunchEditorWidget";
			// Container child PGEManager.LaunchEditorWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.editorVerLbl = new global::Gtk.Label ();
			this.editorVerLbl.Name = "editorVerLbl";
			this.editorVerLbl.LabelProp = "PGE Editor Version: {0}";
			this.vbox3.Add (this.editorVerLbl);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.editorVerLbl]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.engineVerLbl = new global::Gtk.Label ();
			this.engineVerLbl.Name = "engineVerLbl";
			this.engineVerLbl.LabelProp = "PGE Engine Version: {0}";
			this.vbox3.Add (this.engineVerLbl);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.engineVerLbl]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.launchEditorBtn = new global::Gtk.Button ();
			this.launchEditorBtn.CanFocus = true;
			this.launchEditorBtn.Name = "launchEditorBtn";
			this.launchEditorBtn.UseUnderline = true;
			this.launchEditorBtn.Label = "Launch Editor";
			this.hbox2.Add (this.launchEditorBtn);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.launchEditorBtn]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.launchEngineBtn = new global::Gtk.Button ();
			this.launchEngineBtn.CanFocus = true;
			this.launchEngineBtn.Name = "launchEngineBtn";
			this.launchEngineBtn.UseUnderline = true;
			this.launchEngineBtn.Label = "Launch Engine";
			this.hbox2.Add (this.launchEngineBtn);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.launchEngineBtn]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.hbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hbox2]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
