
// This file has been generated by the GUI designer. Do not modify.
namespace PGEManager
{
	public partial class InitialRun
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGEManager.InitialRun
			this.Name = "PGEManager.InitialRun";
			this.Title = "InitialRun";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
