
// This file has been generated by the GUI designer. Do not modify.
namespace PGEManager
{
	public partial class PrettySetupWindow
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label lblWhereIsPGE;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.RadioButton thisPathRadiobutton;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.Button browseButton;
		
		private global::Gtk.RadioButton winRegKeyPath;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Button nextButton;
		
		private global::Gtk.Label GtkLabel3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGEManager.PrettySetupWindow
			this.Name = "PGEManager.PrettySetupWindow";
			this.Title = "PGE Manager Setup";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child PGEManager.PrettySetupWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame1.LabelXalign = 0.5F;
			this.frame1.LabelYalign = 0F;
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblWhereIsPGE = new global::Gtk.Label ();
			this.lblWhereIsPGE.Name = "lblWhereIsPGE";
			this.lblWhereIsPGE.LabelProp = "Where is your PGE located?";
			this.vbox2.Add (this.lblWhereIsPGE);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.lblWhereIsPGE]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.thisPathRadiobutton = new global::Gtk.RadioButton ("Here:");
			this.thisPathRadiobutton.WidthRequest = 1;
			this.thisPathRadiobutton.CanFocus = true;
			this.thisPathRadiobutton.Name = "thisPathRadiobutton";
			this.thisPathRadiobutton.DrawIndicator = true;
			this.thisPathRadiobutton.UseUnderline = true;
			this.thisPathRadiobutton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox2.Add (this.thisPathRadiobutton);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.thisPathRadiobutton]));
			w2.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox2.Add (this.entry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entry1]));
			w3.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.browseButton = new global::Gtk.Button ();
			this.browseButton.CanFocus = true;
			this.browseButton.Name = "browseButton";
			this.browseButton.UseUnderline = true;
			this.browseButton.Label = "Browse";
			this.hbox2.Add (this.browseButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.browseButton]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.winRegKeyPath = new global::Gtk.RadioButton ("From Registry: ");
			this.winRegKeyPath.CanFocus = true;
			this.winRegKeyPath.Name = "winRegKeyPath";
			this.winRegKeyPath.DrawIndicator = true;
			this.winRegKeyPath.UseUnderline = true;
			this.winRegKeyPath.Group = this.thisPathRadiobutton.Group;
			this.vbox2.Add (this.winRegKeyPath);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.winRegKeyPath]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.nextButton = new global::Gtk.Button ();
			this.nextButton.WidthRequest = 90;
			this.nextButton.CanFocus = true;
			this.nextButton.Name = "nextButton";
			this.nextButton.UseUnderline = true;
			this.nextButton.Label = "Next";
			this.hbox3.Add (this.nextButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.nextButton]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.GtkAlignment.Add (this.vbox2);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.WidthRequest = 123;
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = "<b>PGE Manager Setup</b>";
			this.GtkLabel3.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel3;
			this.vbox1.Add (this.frame1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 491;
			this.DefaultHeight = 157;
			this.Show ();
			this.entry1.Changed += new global::System.EventHandler (this.OnEntry1Changed);
			this.browseButton.Clicked += new global::System.EventHandler (this.OnBrowseButtonClicked);
			this.winRegKeyPath.Toggled += new global::System.EventHandler (this.OnWinRegKeyPathToggled);
			this.nextButton.Clicked += new global::System.EventHandler (this.OnNextButtonClicked);
		}
	}
}
