
// This file has been generated by the GUI designer. Do not modify.
namespace PGEManager
{
	public partial class ViewPackInfoWindow
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PGEManager.ViewPackInfoWindow
			this.Name = "PGEManager.ViewPackInfoWindow";
			this.Title = "ViewPackInfoWindow";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PGEManager.ViewPackInfoWindow.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow.Add (this.treeview1);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 494;
			this.DefaultHeight = 528;
			this.Show ();
		}
	}
}
