/*****************************************************************
     Automatically generated by _common/res_generator utility
     Suggested to DONT EDIT THIS
     Edit the _common/res_generator/res_generator.cpp instead
 *****************************************************************/

#include <stdio.h>
#include <string>
#include "resource_data.h"
#include "resource.h"

bool RES_getMem(const char* file, unsigned char* &mem, size_t &size)
{
   std::unordered_map<std::string, FileEntry>::iterator f = filesMap.find(file);
   if(f == filesMap.end())
       return false;

   FileEntry& e = f->second;
   mem = e.array;
   size = e.size;
   return true;
}

