/*****************************************************************
     Automatically generated by _common/res_generator utility
     Suggested to DONT EDIT THIS
     Edit the _common/res_generator/res_generator.cpp instead
 *****************************************************************/

#include <stdio.h>

extern FILE* RES_open(const char* file);
extern void RES_getMem(const char* file, char* &mem, size_t &size);

