# Major
set(TRANSLATOR_VERSION_1 0)
# Minor
set(TRANSLATOR_VERSION_2 1)
# Revision
set(TRANSLATOR_VERSION_3 0)
# Patch
set(TRANSLATOR_VERSION_4 0)
# Type of version: "-alpha","-beta","-dev", or "" aka "release"
set(TRANSLATOR_VERSION_REL "-beta2")

add_definitions(-DTRANSLATOR_VERSION_1=${TRANSLATOR_VERSION_1})
add_definitions(-DTRANSLATOR_VERSION_2=${TRANSLATOR_VERSION_2})
add_definitions(-DTRANSLATOR_VERSION_3=${TRANSLATOR_VERSION_3})
add_definitions(-DTRANSLATOR_VERSION_4=${TRANSLATOR_VERSION_4})
add_definitions(-DTRANSLATOR_VERSION_REL=${TRANSLATOR_VERSION_REL})

set(TRANSLATOR_VERSION_STRING "${TRANSLATOR_VERSION_1}.${TRANSLATOR_VERSION_2}")

if(NOT ${TRANSLATOR_VERSION_3} EQUAL 0 OR NOT ${TRANSLATOR_VERSION_4} EQUAL 0)
    string(CONCAT TRANSLATOR_VERSION_STRING "${TRANSLATOR_VERSION_STRING}" ".${TRANSLATOR_VERSION_3}")
endif()

if(NOT ${TRANSLATOR_VERSION_4} EQUAL 0)
    string(CONCAT TRANSLATOR_VERSION_STRING "${TRANSLATOR_VERSION_STRING}" ".${TRANSLATOR_VERSION_4}")
endif()

if(NOT "${TRANSLATOR_VERSION_REL}" STREQUAL "")
    string(CONCAT TRANSLATOR_VERSION_STRING "${TRANSLATOR_VERSION_STRING}" "${TRANSLATOR_VERSION_REL}")
endif()

message("== Translator version ${TRANSLATOR_VERSION_STRING} ==")
